name: CI

on: [push, pull_request]

jobs:
  setup-configs:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy: 
      matrix: 
        os: [ubuntu-latest, macos-latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Run a one-line script
        run: echo Hello, world!
