name: CI
on: [push, pull_request]

jobs:
  setup-configs:
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 30
    strategy: 
      matrix: 
        config: 
          - os: macos-latest
            kind: mac
          - os: ubuntu-latest
            kind: linux
    steps:
      - uses: actions/checkout@v2
      - name: Setup configs
        env:
          os_type: ${{ format('all-{0}', matrix.config.kind) }}
        run: make $os_type
 

